import type { Metadata } from "next";
import { AppProviders } from './providers';
import "./globals.css";

export const metadata: Metadata = {
  title: "Real Time Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
